# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [2]:
import numpy as np
arr1=np.random.randint(1,100,(3,3))
arr1

array([[98, 61, 58],
       [37, 39, 86],
       [20, 58, 94]])

# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.



In [3]:
import numpy as np
array_1d = np.arange(10)
array_2x5 = np.reshape(array_1d, (2, 5))
array_5x2 = np.reshape(array_1d, (5, 2))

array_1d, array_2x5, array_5x2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [24]:
import numpy as np

arr_4x4 = np.random.rand(4, 4)
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)

arr_4x4, arr_6x6

(array([[0.84073803, 0.84341928, 0.64459986, 0.39657653],
        [0.92436043, 0.70506668, 0.79515278, 0.55346694],
        [0.70636363, 0.33206968, 0.56883995, 0.8049944 ],
        [0.21788267, 0.02008866, 0.96138123, 0.97909961]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.84073803, 0.84341928, 0.64459986, 0.39657653,
         0.        ],
        [0.        , 0.92436043, 0.70506668, 0.79515278, 0.55346694,
         0.        ],
        [0.        , 0.70636363, 0.33206968, 0.56883995, 0.8049944 ,
         0.        ],
        [0.        , 0.21788267, 0.02008866, 0.96138123, 0.97909961,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [6]:
import numpy as np
array = np.arange(10, 60, 5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

In [11]:
import numpy as np
arr_str=np.array(['python','numpy','pandas'])
uppercase_array = np.char.upper(arr_str)
lowercas_array = np.char.lower(arr_str)
titlecase_array = np.char.title(arr_str)
arr_str,uppercase_array,lowercas_array,titlecase_array

(array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [13]:
import numpy as np

words = np.array(['pwskill', 'Ajay', 'datascience'])
spaced_words = np.char.join(' ', words)
words
spaced_words

array(['p w s k i l l', 'A j a y', 'd a t a s c i e n c e'], dtype='<U21')

## 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [22]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array1,array2
add=array1+array2
sub=array1-array2
mul=array1*array2
div=array1/array2
add,sub,mul,div

(array([[ 8, 10, 12],
        [14, 16, 18]]),
 array([[-6, -6, -6],
        [-6, -6, -6]]),
 array([[ 7, 16, 27],
        [40, 55, 72]]),
 array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]))

# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [25]:
import numpy as np
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
identity_matrix, diagonal_elements

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [30]:
import numpy as np
arr1=np.random.randint(0,1000,100)
arr1
for num in arr1:
    if num > 1:
        for i in range(2, int(num ** 0.5) + 1):
            if num % i == 0:
                break

primes = [num for num in array if is_prime(num)]
print("Array:", arr1)
print("Prime numbers:", primes)


Array: [232 441 128  50 445 389 606  48 523 961 335 675 413 728 324  81  19 465
 242  62 547 179 765 136 824 535 956 351 838 612 400 445 934  68   7 802
 865 423 699 208   2 358 482 106 565 590 490 244 895  16 784 431 475 785
 730 658  49 854 267 760 627 439 853 549 538 484 247 203 190 234 734 856
 533 667 874 410 363 654 121 769 945 410 612  82 522 483 262 359 127 807
 209 114 903 340  94 839 800 646 171 240]
Prime numbers: [857, 431, 359, 347, 149, 811, 43, 677, 337, 433, 701, 223]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [32]:
import numpy as np
temp = np.random.uniform(low=-10, high=35, size=30)
temp_reshaped = temp.reshape(5,6)
weekly_averages = temp_reshaped.mean(axis=1)
print("Daily temperatures:", temp)
print("Weekly averages:", weekly_averages)


Daily temperatures: [-1.76607236 -0.68134088  4.50049271 -1.95179705 -1.823306    7.5663906
 22.01038231 13.4241369   6.59164575  2.95090365 -5.87011146 29.17902408
  4.23514979 14.56101447 18.01126817 12.01435945 -0.27015293 17.52491819
 -7.70597975 10.97728272 -8.6091518  30.8333572  11.29512051 34.35275037
 -9.71325195 18.88688757 -5.25879872 -6.73156702 -6.06087393 10.31565417]
Weekly averages: [ 0.97406117 11.38099687 11.01275952 11.85722988  0.23967502]
